DB:
  USER: postgres
  NAME: reimbursement_test
  HOST: localhost
  PASSWORD: postgres
  PORT: 5432
  SSL_MODE: disable
LOG:
  LEVEL: debug
SERVER:
  HTTP_PORT: 8080
MIGRATION:
  FILE_PATH: "db/migration"