name: Reimbursement Project
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: reimbursement
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      golang:
        image: golang:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate

      - name: Build Project
        run: go build -v ./...

      - name: Run Migrations
        run: make migrate-up

      - name: Run Tests
        run: go test -v ./...

  create-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add SSH Key To Known Host
        env:
          SSH_PUBLIC: ${{secrets.SSH_PUBLIC}}
          SSH_PRIVATE: ${{secrets.SSH_PRIVATE}}
          HOST_SSH: ${{ secrets.SSH_HOST }}
        run: rm -rf .ssh && mkdir ~/.ssh && cd ~/.ssh && ls && echo $SSH_PUBLIC > id_rsa.pub &&  echo $SSH_PRIVATE > id_rsa && echo $HOST_SSH > known_hosts && chmod 400 ~/.ssh/id_rsa

      - name: SSH connect to the timetracker instance
        run: ssh rajat@35.200.199.253