name: Reimbursement Project
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: reimbursement
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      golang:
        image: golang:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate.linux-amd64 /usr/bin/migrate

      - name: Build Project
        run: go build -v .

      - name: Run Migrations
        run: make migrate-up

      - name: Run Tests
        run: go test -v ./...

  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: go build .
      - name: Add SSH Key To Runner
        env:
          SSH_PUBLIC: ${{secrets.SSH_PUBLIC}}
          SSH_PRIVATE: ${{secrets.SSH_PRIVATE}}
          SSH_HOST: ${{secrets.SSH_HOST}}
        run: |
          mkdir ~/.ssh
          echo $SSH_PUBLIC > ~/.ssh/id_rsa.pub
          echo "${{secrets.SSH_PRIVATE}}" > ~/.ssh/id_rsa
          echo $SSH_HOST > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          ls ~/.ssh
      - name: Move Binary to Remote Instance
        run: scp -o StrictHostKeyChecking=no reimbursement_backend sanjay@35.200.199.253:/home/sanjay/reimbursement_backend
      - name: Connect to Instance
        run: ssh -o StrictHostKeyChecking=no sanjay@35.200.199.253
      - name: Run The Binary
        run: ./reimbursement_backend &
      - name: Run The Binary
        run: curl http://localhost:9000/hello