name: Deploy to Production
on: [workflow_dispatch]
jobs:
  build:
    name: Build & Test
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: reimbursement
          POSTGRES_PASSWORD: password
          POSTGRES_DB: reimbursement_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      golang:
        image: golang:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.2'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-arm64.tar.gz | tar xvz
          sudo mv migrate.linux-arm64 /usr/bin/migrate

      - name: Build Project
        run: env GOOS=linux GOARCH=amd64 go build -v .

      - name: Run Migrations
        run: make migrate-up-test-database

      - name: Run Tests
        run: go test -v ./...

      - uses: actions/upload-artifact@master
        with:
          name: binary_file
          path: reimbursement_backend

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/download-artifact@v3
        with:
          name: binary_file
          path: .

      - name: Add SSH Key To Runner
        env:
          REIMBURSEMENT_PRIVATE_KEY: ${{secrets.REIMBURSEMENT_PRIVATE_KEY}}
        run: |
          echo "${{secrets.REIMBURSEMENT_PRIVATE_KEY}}" > reimbursement_id_rsa
          chmod 600 reimbursement_id_rsa

      - name: Create config.yaml file
        run: |
          touch config.yaml
          echo "HTTP_PORT: ${{secrets.SERVER_PORT}}" >> config.yaml
          echo "GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}" >> config.yaml
          echo "DB:" >> config.yaml
          echo "  USER: ${{secrets.DB_USER}}" >> config.yaml
          echo "  NAME: ${{secrets.DB_NAME}}" >> config.yaml
          echo "  HOST: ${{secrets.DB_HOST}}" >> config.yaml
          echo "  PASSWORD: ${{secrets.DB_PASSWORD}}" >> config.yaml
          echo "  PORT: ${{secrets.DB_PORT}}" >> config.yaml
          echo "  SSL_MODE: ${{secrets.SSL_MODE}}" >> config.yaml
          echo "LOG:" >> config.yaml
          echo "  LEVEL: ${{secrets.LOG_LEVEL}}" >> config.yaml
          echo "MIGRATION:" >> config.yaml
          echo "  FILE_PATH: \"db/migration\"" >> config.yaml
          echo "EMAIL:" >> config.yaml
          echo "  ADMIN_EMAILS: ${{secrets.PRODUCTION_ADMIN_EMAILS}}" >> config.yaml
          echo "  CA_EMAIL: ${{secrets.CA_EMAIL}}" >> config.yaml

      - name: Remove previous binary, database migrations and config.yaml file from remote instance
        run: ssh -i reimbursement_id_rsa -o StrictHostKeyChecking=no reimbursement@${{secrets.BACKEND_INSTANCE_IP}} "rm -rf config.yaml;rm -rf reimbursement_backend;rm -rf db/migration/*"

      - name: Kill the process
        continue-on-error: true
        run: ssh -i reimbursement_id_rsa -o StrictHostKeyChecking=no reimbursement@${{secrets.BACKEND_INSTANCE_IP}} "sudo kill -9 $(sudo lsof -t -i:${{secrets.SERVER_PORT}})"

      - name: Move config.yaml File to Remote
        run: scp -i reimbursement_id_rsa -o StrictHostKeyChecking=no config.yaml reimbursement@${{secrets.BACKEND_INSTANCE_IP}}:/home/reimbursement/config.yaml

      - name: Move Binary to Remote Instance
        run: scp -i reimbursement_id_rsa -o StrictHostKeyChecking=no reimbursement_backend reimbursement@${{secrets.BACKEND_INSTANCE_IP}}:/home/reimbursement/reimbursement_backend

      - name: Move Migrations to Remote Instance
        run: |
          ssh -i reimbursement_id_rsa -o StrictHostKeyChecking=no reimbursement@${{secrets.BACKEND_INSTANCE_IP}} "mkdir -p db/migration"
          scp -i reimbursement_id_rsa -o StrictHostKeyChecking=no db/migration/* reimbursement@${{secrets.BACKEND_INSTANCE_IP}}:/home/reimbursement/db/migration

      - name: Change file access mode
        run: ssh -i reimbursement_id_rsa -o StrictHostKeyChecking=no reimbursement@${{secrets.BACKEND_INSTANCE_IP}} "chmod +x reimbursement_backend;chmod +x config.yaml;"

      - name: Run Migrations
        run: ssh -i reimbursement_id_rsa -o StrictHostKeyChecking=no reimbursement@${{secrets.BACKEND_INSTANCE_IP}} "./reimbursement_backend migrate-down"

      - name: Start the service to run the updated binary
        run: ssh -i reimbursement_id_rsa -o  StrictHostKeyChecking=no reimbursement@${{secrets.BACKEND_INSTANCE_IP}} "sudo systemctl restart reimbursement.service"
